info:
  component: Config Server
spring:
  application:
    name: configserver
  jmx:
    default_domain: cloud.config.server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/spring-cloud-samples/config-repo
  banner:
    location: "file:/config/banner.txt"
  main:
    banner-mode: console  # values off console log
#  profiles:
#    active: vault
management:
  context_path: /admin
 
